In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [22]:
cols = ['engine_id', 'cycle', 'op_setting_1', 'op_setting_2', 'op_setting_3', 'sensor_1', 'sensor_2', 'sensor_3',
        'sensor_4', 'sensor_5', 'sensor_6', 'sensor_7', 'sensor_8', 'sensor_9', 'sensor_10', 'sensor_11', 'sensor_12',
        'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20',
        'sensor_21', 'sensor_22', 'sensor_23', 'sensor_24', 'sensor_25', 'sensor_26']

df = pd.read_csv('train_FD001.txt', sep = ' ', names = cols)
df.head()

,engine_id,cycle,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,sensor_22,sensor_23,sensor_24,sensor_25,sensor_26
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,392,2388,100.0,39.06,23.4190,NaN,NaN,NaN,NaN,NaN
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,392,2388,100.0,39.00,23.4236,NaN,NaN,NaN,NaN,NaN
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,390,2388,100.0,38.95,23.3442,NaN,NaN,NaN,NaN,NaN
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,392,2388,100.0,38.88,23.3739,NaN,NaN,NaN,NaN,NaN
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,393,2388,100.0,38.90,23.4044,NaN,NaN,NaN,NaN,NaN

In [24]:
rul = df.groupby('engine_id')['cycle'].max().reset_index()
rul.columns = ['engine_id', 'max_cycle']
df = df.merge(rul, on='engine_id')
df['RUL'] = df['max_cycle'] - df['cycle']
df.head()

,engine_id,cycle,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_19,sensor_20,sensor_21,sensor_22,sensor_23,sensor_24,sensor_25,sensor_26,max_cycle,RUL
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,100.0,39.06,23.4190,NaN,NaN,NaN,NaN,NaN,192,191
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,100.0,39.00,23.4236,NaN,NaN,NaN,NaN,NaN,192,190
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,100.0,38.95,23.3442,NaN,NaN,NaN,NaN,NaN,192,189
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,100.0,38.88,23.3739,NaN,NaN,NaN,NaN,NaN,192,188
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,100.0,38.90,23.4044,NaN,NaN,NaN,NaN,NaN,192,187

In [25]:
df.corr(numeric_only = True)

,engine_id,cycle,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_19,sensor_20,sensor_21,sensor_22,sensor_23,sensor_24,sensor_25,sensor_26,max_cycle,RUL
engine_id,1.000000,0.078753,-0.017895,-0.006197,NaN,NaN,0.014133,0.012621,0.026116,NaN,...,NaN,-0.020589,-0.016465,NaN,NaN,NaN,NaN,NaN,0.216858,0.078753
cycle,0.078753,1.000000,-0.004527,0.016132,NaN,NaN,0.549898,0.543947,0.624577,NaN,...,NaN,-0.583597,-0.585923,NaN,NaN,NaN,NaN,NaN,0.363152,-0.736241
op_setting_1,-0.017895,-0.004527,1.000000,0.011660,NaN,NaN,0.009030,-0.005651,0.009544,NaN,...,NaN,-0.005713,-0.014559,NaN,NaN,NaN,NaN,NaN,-0.010636,-0.003198
op_setting_2,-0.006197,0.016132,0.011660,1.000000,NaN,NaN,0.007266,0.009068,0.014673,NaN,...,NaN,-0.010554,-0.007846,NaN,NaN,NaN,NaN,NaN,0.019530,-0.001948
op_setting_3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_2,0.014133,0.549898,0.009030,0.007266,NaN,NaN,1.000000,0.602610,0.714949,NaN,...,NaN,-0.661841,-0.668050,NaN,NaN,NaN,NaN,NaN,-0.077909,-0.606484
sensor_3,0.012621,0.543947,-0.005651,0.009068,NaN,NaN,0.602610,1.000000,0.678413,NaN,...,NaN,-0.625941,-0.633901,NaN,NaN,NaN,NaN,NaN,-0.055863,-0.584520
sensor_4,0.026116,0.624577,0.009544,0.014673,NaN,NaN,0.714949,0.678413,1.000000,NaN,...,NaN,-0.748067,-0.745193,NaN,NaN,NaN,NaN,NaN,-0.074860,-0.678948
sensor_5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_6,0.026431,0.105980,-0.001340,0.014355,NaN,NaN,0.132242,0.116039,0.150480,NaN,...,NaN,-0.141419,-0.137419,NaN,NaN,NaN,NaN,NaN,-0.030798,-0.128348
sensor_7,-0.032073,-0.595914,-0.009437,-0.016678,NaN,NaN,-0.702136,-0.664595,-0.793130,NaN,...,NaN,0.736163,0.737447,NaN,NaN,NaN,NaN,NaN,0.084412,0.657223
sensor_8,0.039929,0.475977,-0.000427,0.013285,NaN,NaN,0.662325,0.602481,0.746852,NaN,...,NaN,-0.687030,-0.688840,NaN,NaN,NaN,NaN,NaN,-0.121149,-0.563968
sensor_9,-0.052053,0.443999,-0.004279,-0.005425,NaN,NaN,0.273764,0.322964,0.297429,NaN,...,NaN,-0.285280,-0.292795,NaN,NaN,NaN,NaN,NaN,0.074208,-0.390102
sensor_10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_11,0.024707,0.634385,0.011658,0.011690,NaN,NaN,0.740020,0.695900,0.830136,NaN,...,NaN,-0.771510,-0.772554,NaN,NaN,NaN,NaN,NaN,-0.085148,-0.696228
sensor_12,-0.031882,-0.611354,-0.001491,-0.010923,NaN,NaN,-0.724578,-0.680307,-0.815591,NaN,...,NaN,0.751943,0.756263,NaN,NaN,NaN,NaN,NaN,0.083477,0.671983
sensor_13,0.044230,0.477523,0.002318,0.018156,NaN,NaN,0.661792,0.600963,0.745158,NaN,...,NaN,-0.686172,-0.688948,NaN,NaN,NaN,NaN,NaN,-0.117094,-0.562569
sensor_14,-0.059473,0.370324,-0.004469,-0.006310,NaN,NaN,0.179752,0.237137,0.190748,NaN,...,NaN,-0.187364,-0.192415,NaN,NaN,NaN,NaN,NaN,0.087504,-0.306769
sensor_15,0.022486,0.588676,0.007652,0.014156,NaN,NaN,0.675975,0.639921,0.758459,NaN,...,NaN,-0.707671,-0.704043,NaN,NaN,NaN,NaN,NaN,-0.074337,-0.642667
sensor_16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_17,0.013513,0.566995,0.002599,0.012280,NaN,NaN,0.629886,0.600017,0.703499,NaN,...,NaN,-0.651021,-0.658710,NaN,NaN,NaN,NaN,NaN,-0.053915,-0.606154
sensor_18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_20,-0.020589,-0.583597,-0.005713,-0.010554,NaN,NaN,-0.661841,-0.625941,-0.748067,NaN,...,NaN,1.000000,0.693480,NaN,NaN,NaN,NaN,NaN,0.063102,0.629428
sensor_21,-0.016465,-0.585923,-0.014559,-0.007846,NaN,NaN,-0.668050,-0.633901,-0.745193,NaN,...,NaN,0.693480,1.000000,NaN,NaN,NaN,NaN,NaN,0.068482,0.635662
sensor_22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max_cycle,0.216858,0.363152,-0.010636,0.019530,NaN,NaN,-0.077909,-0.055863,-0.074860,NaN,...,NaN,0.063102,0.068482,NaN,NaN,NaN,NaN,NaN,1.000000,0.363152
RUL,0.078753,-0.736241,-0.003198,-0.001948,NaN,NaN,-0.606484,-0.584520,-0.678948,NaN,...,NaN,0.629428,0.635662,NaN,NaN,NaN,NaN,NaN,0.363152,1.000000